[build]
  command = "yarn deploy"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "pk_28559d25f0fa9004828a707abba2aa96385bf499ef764"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_eGGCmLBxB5xTg8V6ghctU9Le
